---
title: "Trait mindfulness increases self-perceived scholastic competence in adolescent girls" 
author: "Clare McCann & Kate Mills"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)
```

```{r Load Required Packages, message=FALSE, warning=FALSE, include=FALSE}
## Load required packages ##
packages <-  c("tidyverse", "lavaan",
               "reshape2",
               "nlme", "lme4",
               "data.table", "psych",
               "parallel","lubridate",
               "mgcv", "ggpubr", "broom", "table1", "ggeffects")
lapply(packages, library, character.only = TRUE)
```

Set root path for kate
```{r}
#kate's root path
root_path="/Volumes/devbrainlab/Clare/honors_cm/"
```

Set root path for Clare
```{r}
root_path="~/Documents/Honors_Project/honors_cm/"
```


Load datasets
```{r}

##pulling CSV files & calculating cronbach alpha

CAMM_W1<-read.csv(paste0(root_path,"CAMM_Wave1.csv"),
                  stringsAsFactors = FALSE) %>%
              select(tagid, CAMM_W1)

#CAMM_W1 <- CAMM_W1[,c(3:12)]

#CAMM_cron_1 <-  alpha(CAMM_W1, na.rm = TRUE, check.keys = TRUE)

CAMM_W2<-read.csv(paste0(root_path,"CAMM_Wave2.csv"),
                  stringsAsFactors = FALSE) %>%
              select(tagid, CAMM_W2)

#CAMM_W2 <- CAMM_W2[,c(3:12)]

#CAMM_cron_2 <-  alpha(CAMM_W2, na.rm = TRUE, check.keys = TRUE)

CAMM_W3<-read.csv(paste0(root_path,"CAMM_Wave3.csv"),
                  stringsAsFactors = FALSE)  %>%
              select(tagid, CAMM_W3)

#CAMM_W3 <- CAMM_W3[,c(3:12)]

#CAMM_cron_3 <-  alpha(CAMM_W3, na.rm = TRUE, check.keys = TRUE)

SPPA_W1<-read.csv(paste0(root_path,"SPPA_Wave1.csv"),
                  stringsAsFactors = FALSE)  %>%
              select(tagid, SC_W1)

##SC_W1 <- SPPA_W1[,c(86, 94, 102, 110, 118)]

##SC_cron_W1 <- alpha(SC_W1, na.rm = TRUE, check.keys = TRUE)

SPPA_W2<-read.csv(paste0(root_path,"SPPA_Wave2.csv"),
                  stringsAsFactors = FALSE)  %>%
              select(tagid, SC_W2)

#SC_W2 <- SPPA_W2[,c(86, 94, 102, 110, 118)]

#SC_cron_W2 <- alpha(SC_W2, na.rm = TRUE, check.keys = TRUE)

SPPA_W3<-read.csv(paste0(root_path,"SPPA_Wave3.csv"),
                  stringsAsFactors = FALSE) %>%
              select(tagid, SC_W3)

##SC_W3 <- SPPA_W3[,c(86, 94, 102, 110, 118)]

##SC_cron_W3 <- alpha(SC_W3, na.rm = TRUE, check.keys = TRUE)


SES <- read.csv(paste0(root_path,"Wave 1 SES.csv"),
                stringsAsFactors = FALSE) %>% 
  select(tagid, W1_Income) #Long 

Age <- read.csv(paste0(root_path,"Age.csv"),
                stringsAsFactors = FALSE) %>% 
  select(tagid, wave, age) %>% 
  mutate(wave=paste0("W",wave))

#Age <-na.omit(Age)

Menarche <- read.csv(
  paste0(root_path,"Age_at_menarche_short_finalizing copy.csv"),
  stringsAsFactors = FALSE) %>% 
  select(tagid, aam_final) #Long

School_Transitions <- read.csv(paste0(root_path,"Grade Transitions CM Honors.csv"),
                               stringsAsFactors = FALSE) %>% 
  select(tagid, Transitioned_W1, Transitioned_W2, Transitioned_W3)

Grades_W1 <-read.csv(paste0(root_path,"W1_School_Info.csv"),
                  stringsAsFactors = FALSE)  %>%
              select(tagid, Grades_Average)

Grades_W2 <-read.csv(paste0(root_path,"W2_School_Info.csv"),
                  stringsAsFactors = FALSE)  %>%
              select(tagid, Grades_Average) 

Grades_W3 <-read.csv(paste0(root_path,"W3_School_Info.csv"),
                  stringsAsFactors = FALSE)  %>%
              select(tagid, Grades_Average) 

Grades_W1$Grades_Average

               

#School_Transitions <-na.omit(School_Transitions)


#Removing underscores from id

School_Transitions <-School_Transitions %>%
  mutate(no_underscores=paste0("TAG",
                               substring(tagid,first=5,last=length(tagid))))

Grades_W1 <-Grades_W1 %>%
  mutate(no_underscores=paste0("TAG",
                               substring(tagid,first=5,last=length(tagid))))


Grades_W2 <-Grades_W2 %>%
  mutate(no_underscores=paste0("TAG",
                               substring(tagid,first=5,last=length(tagid))))

Grades_W3 <-Grades_W3 %>%
  mutate(no_underscores=paste0("TAG",
                               substring(tagid,first=5,last=length(tagid))))

#Reorganizing columns 

School_Transitions <- School_Transitions[,-1]
School_Transitions <- School_Transitions[c(4,1,2,3)]

colnames(School_Transitions)[1] <- "tagid"

Grades_W1 <- Grades_W1[,-1]
Grades_W2 <- Grades_W2[,-1]
Grades_W3 <- Grades_W3[,-1]

Grades_W1 <- Grades_W1[c(2,1)]
Grades_W2 <- Grades_W2[c(2,1)]
Grades_W3 <- Grades_W3[c(2,1)]

colnames(Grades_W1)[1] <- "tagid"
colnames(Grades_W2)[1] <- "tagid"
colnames(Grades_W3)[1] <- "tagid"

Grades_W1$Grades_Average <- as.character(Grades_W1$Grades_Average)
Grades_W2$Grades_Average <- as.character(Grades_W2$Grades_Average)
Grades_W3$Grades_Average <- as.character(Grades_W3$Grades_Average)

colnames(Grades_W1)[2] <- "Grades_W1"
colnames(Grades_W2)[2] <- "Grades_W2"
colnames(Grades_W3)[2] <- "Grades_W3"



#coding for transitions 

# 1 = transitioned to middle school 
# 2 = transitioned to high school 
# 0 = no transition prior to wave 


```

Make long datasets
```{r}
#Creating Long Data Set for MLM 
CAMM_long<-full_join(CAMM_W1,full_join(CAMM_W2,CAMM_W3)) %>%
  gather(Wave_CAMM, CAMM, CAMM_W1:CAMM_W3) %>%
  mutate(wave = substr(Wave_CAMM, 7, 7)) %>%
  select(-Wave_CAMM)

SC_long<-full_join(SPPA_W1,full_join(SPPA_W2,SPPA_W3)) %>%
  gather(Wave_SC, SC, SC_W1:SC_W3) %>%
  mutate(wave = substr(Wave_SC, 5, 5)) %>%
  select(-Wave_SC)

Grades_long <- full_join(Grades_W1, full_join(Grades_W2,Grades_W3)) %>%
  gather(Wave_Grades, Grades, Grades_W1:Grades_W3) %>%
  mutate(wave = substr(Wave_Grades, 9, 9)) %>%
  select(-Wave_Grades)

long_HonorsData <- full_join(CAMM_long, SC_long)
long_HonorsData <- full_join(Grades_long, long_HonorsData, by=c("tagid", "wave")) %>%
  distinct(.)
  
SchoolTransitions_long<-School_Transitions %>% gather(Wave_Transitioned, Transition, Transitioned_W1:Transitioned_W3) %>%
  mutate(wave = substr(Wave_Transitioned, 15, 15)) %>%
  select(-Wave_Transitioned)


long_HonorsData<-full_join(SchoolTransitions_long,long_HonorsData,by=c("tagid", "wave")) %>%
  distinct(.)

Age <- Age %>% mutate(wave = substr(wave, 2, 2))

long_HonorsData <- full_join(long_HonorsData, Age, by=c("tagid", "wave")) %>%
  distinct(.)

long_HonorsData <- full_join(long_HonorsData, SES, by=c("tagid")) %>%
  distinct(.)

long_HonorsData <- full_join(long_HonorsData, Menarche, by=c("tagid")) %>%
  distinct(.)

# remove rows without School Transitions data

long_HonorsData <- long_HonorsData[is.na(long_HonorsData$Transition) == FALSE, ]

# identify participants with duplicate data

#long_HonorsData$tagid_wave <- paste(long_HonorsData$tagid, long_HonorsData$wave, sep="_") # create a new variable that combines subject ID and wave information

#long_HonorsData[duplicated(long_HonorsData$tagid_wave), ] # see duplicated data

# note that duplicated data exists for TAG166 at wave 2. Take the average of all CAMM and SC values
filter(long_HonorsData, tagid == "TAG166" & wave == 2) %>% 
  summarise(mean_CAMM_TAG166 = mean(CAMM),
            mean_SC = mean(SC)) 

# note that mean CAMM = 24.5, mean_SC = 16
# manually replaced all TAG 166, W2 CAMM and SC values with the average across repeated assessments

long_HonorsData[which(long_HonorsData$tagid == "TAG166" & long_HonorsData$wave == 2), ]$CAMM = 24.5
long_HonorsData[which(long_HonorsData$tagid == "TAG166" & long_HonorsData$wave == 2), ]$SC = 16

# now that we've made all the values the same, there should be duplicated rows. remove those duplicated rows
long_HonorsData <- distinct(long_HonorsData)

rm(Age,CAMM_long,CAMM_W1,CAMM_W2,CAMM_W3,Menarche,SC_long,School_Transitions,SchoolTransitions_long, SPPA_W1,SPPA_W2,SPPA_W3,SES)

# Make time-lagged variables

LagWave1<-long_HonorsData%>%
  filter(wave==1) %>%
  mutate(CAMM_lag=CAMM,
         SC_lag=SC,
         wave=as.factor(2)) %>%
  select(tagid,wave,SC_lag,CAMM_lag)


long_HonorsData<-left_join(long_HonorsData,LagWave1,by=c("tagid","wave"))

LagWave2<-long_HonorsData%>%
  filter(wave==2) %>%
  mutate(CAMM_lag=CAMM,
         SC_lag=SC,
         wave=as.factor(3)) %>%
  select(tagid,wave,SC_lag,CAMM_lag)

long_HonorsData<-left_join(long_HonorsData,LagWave2,by=c("tagid","wave")) 

long_HonorsData<-long_HonorsData%>%
  mutate(SC_lag=ifelse(wave==2,SC_lag.x,
                       ifelse(wave==3,SC_lag.y,
                              NA)),
         CAMM_lag=ifelse(wave==2,CAMM_lag.x,
                       ifelse(wave==3,CAMM_lag.y,
                              NA)))

long_HonorsData <- na_if(long_HonorsData, "-3")
long_HonorsData <- na_if(long_HonorsData, "-9")
  #removing extra columns

long_HonorsData<-long_HonorsData %>%
  select(-SC_lag.x,-SC_lag.y,-CAMM_lag.x,-CAMM_lag.y)


```

```{r}

##organizing data

#reording columns

long_HonorsData <- long_HonorsData[c(1,3,2,4,5,6,7,8,9,10,11)]

# renaming columns 

colnames(long_HonorsData)[8] <- "SES"
colnames(long_HonorsData)[9] <- "Age_at_Menarche"
colnames(long_HonorsData)[7]<- "Age_at_Wave"


long_HonorsData$SES <- as.numeric(long_HonorsData$SES)

# removing N/A 
long_HonorsData <- long_HonorsData %>% mutate(SES = na_if(SES, 7))
long_HonorsData <- long_HonorsData %>% mutate(Grades = na_if(Grades, -9))




long_HonorsData$SES<-ordered(as.factor(long_HonorsData$SES))
long_HonorsData$Transition <- as.factor(long_HonorsData$Transition)
long_HonorsData$tagid <- as.factor(long_HonorsData$tagid)
long_HonorsData$wave <- as.factor(long_HonorsData$wave)
long_HonorsData$Grades <- as.factor(long_HonorsData$Grades)
str(long_HonorsData)

# chunking SES brackets, 1&2 = lower income (1), 3=median (2), 4&5=high (3)

long_HonorsData <- long_HonorsData%>%
  mutate(SES=ifelse(SES==2, "Low",
                           ifelse(SES==3, "Middle",
                                  ifelse(SES==4,"High",
                                         ifelse(SES==5,"High",
                                                ifelse(SES==1, "Low",
                              SES)))))) %>%
  mutate(SES=as.factor(SES)) 

long_HonorsData <- long_HonorsData %>%
  mutate(Grades=ifelse(Grades==1, "A",
                           ifelse(Grades==2, "B",
                                  ifelse(Grades==3,"C",
                                         ifelse(Grades==4,"NP",
                                                ifelse(Grades==5,"NP",
                              Grades)))))) %>%
  mutate(Grades=as.factor(Grades))
  





```

Descriptives
```{r}

#visualizing data

library("ggpubr")

ggboxplot(long_HonorsData, x = "wave", y = "Age_at_Wave",
          color = "wave",
          palette = c("#00AFBB", "#E7B800", "#FC4E07"))

ggboxplot(long_HonorsData, x = "wave", y = "CAMM",
          color = "wave",
          palette = c("#00AFBB", "#E7B800", "#FC4E07"))

ggboxplot(long_HonorsData, x = "wave", y = "SC",
          color = "wave",
          palette = c("#00AFBB", "#E7B800", "#FC4E07"))

ggboxplot(long_HonorsData, x = "wave", y = "SC",
          color = "Grades",
          palette = c("#00AFBB", "#E7B800", "#FC4E07", ))
               
```

Analysis using SPPA-SC as dependent variable
```{r}
# making a mean centered age variable 

long_HonorsData$agecenter<-(long_HonorsData$Age_at_Wave-12.5)
long_HonorsData$agecenter.sq<-(long_HonorsData$agecenter*long_HonorsData$agecenter)

#Q1: Does self-perceived scholastic competence change across early adolescence in girls?  

null_model_SC_age_cov<-lme(SC ~ SES+Age_at_Menarche,
                      method="ML",
                      random = ~1|tagid,
                      data=long_HonorsData %>% 
                              filter(!is.na(SC),
                                     !is.na(agecenter),
                                     !is.na(SES),
                                     !is.na(Age_at_Menarche)))

lin_model_SC_age_cov<-lme(SC ~ SES+Age_at_Menarche+agecenter,
                      method="ML",
                      random = ~1|tagid,
                      data=long_HonorsData %>% 
                              filter(!is.na(SC),
                                     !is.na(agecenter),
                                     !is.na(SES),
                                     !is.na(Age_at_Menarche)))
summary(lin_model_SC_age_cov)

quad_model_SC_age_cov<-lme(SC ~ SES+Age_at_Menarche+agecenter+agecenter.sq,
                      method="ML",
                      random = ~1|tagid,
                      data=long_HonorsData %>% 
                             filter(!is.na(SC),
                                     !is.na(agecenter),
                                     !is.na(SES),
                                     !is.na(Age_at_Menarche)))
summary(quad_model_SC_age_cov)

anova(null_model_SC_age_cov,lin_model_SC_age_cov, quad_model_SC_age_cov)

# graph for question 1 

age_by_SC<-ggplot(data=long_HonorsData,
       aes(x=Age_at_Wave,
           y=SC))+
  xlim(9.5,16.5)+
  xlab("Age (years)")+
  ylim(5,20)+
  ylab("Scholastic Competence")+
  geom_line(aes(group=tagid),size=.5,alpha=0.3,colour="#82204A")+
  geom_point(aes(group=tagid),size=3,alpha=0.3,colour="#82204A")+
  theme(axis.title = element_text(face = "bold")) + 
  theme_minimal()

  
age_by_SC

# saving graph as tiff

ggsave("Age_by_SC.tiff", width= 6, height=4, units= 'in', dpi=600, bg = "transparent")

# question 1 without covariates

null_model_SC_age<-lme(SC ~ 1,
                      method="ML",
                      random = ~1|tagid,
                      data=long_HonorsData %>% 
                              filter(!is.na(SC),
                                     !is.na(agecenter)))

lin_model_SC_age<-lme(SC ~ agecenter,
                      method="ML",
                      random = ~1|tagid,
                      data=long_HonorsData %>% 
                              filter(!is.na(SC),
                                     !is.na(agecenter)))


quad_model_SC_age<-lme(SC ~ agecenter+agecenter.sq,
                      method="ML",
                      random = ~1|tagid,
                      data=long_HonorsData %>% 
                             filter(!is.na(SC),
                                     !is.na(agecenter)))

anova(null_model_SC_age, lin_model_SC_age, quad_model_SC_age)

#Q2: How much do prior levels of self-reported mindfulness predict self-perceived scholastic competence?

#removing wave 1 from graph since time-lagged 

try <- long_HonorsData %>% 
  filter(!(wave %in% c("1"))) 
  
# graph for question 2

CAMMlag_by_SC<-ggplot(data=try,
       aes(x=CAMM_lag,
           y=SC))+
  xlim(0,40)+
  xlab("CAMM (prior timepoint)")+
  ylim(5,20)+
  ylab("Scholastic Competence")+
  geom_line(aes(group=tagid),size=.3,alpha=0.3)+
  geom_point(aes(group=tagid,colour=wave, shape=wave),size=2,alpha=0.3)+
  geom_smooth(method='lm', formula= y~x)+
  theme(axis.title = element_text(face = "bold"), legend.text = element_text(face = "bold"), legend.title = element_text(face = "bold")) +
  scale_colour_manual(name = "Wave",labels=c("2","3"), values= c("#E7B800", "#FC4E07"))+
   scale_shape(name= "Wave",
              labels=c("2",
                       "3")) + theme_minimal()

#saving graph for question 2

ggsave("CAMM_by_SC.tiff",
      plot=CAMMlag_by_SC,
      bg = "transparent",
      width= 6, height=4, units= 'in', dpi=600)


# First thing is to report comparing null model to one including prior CAMM as predictor
# with prior SC as covariate
  
# Null model filtering NAs in lags and contemporaneous measures of SC and CAMM without covariates
null_model_SC<-lme(SC ~ 1,
                      method="ML",
                      random = ~1|tagid,
                      data=long_HonorsData %>% 
                              filter(!is.na(SC),
                                     !is.na(CAMM_lag),
                                     !is.na(SC_lag)))

# Linear model of prior CAMM predicting SC after controlling for prior SC
lin_model_SC_CAMM<-lme(SC ~ SC_lag + CAMM_lag,
                      method = "ML",
                      random = ~1|tagid,
                      data=long_HonorsData %>% 
                              filter(!is.na(SC),
                                     !is.na(SC_lag),
                                     !is.na(CAMM_lag)))

# Comapre null to linear model w/ predictors and the linear model is better
anova(null_model_SC,lin_model_SC_CAMM)

summary(lin_model_SC_CAMM)

# Now, examine with all the preregistered covariates included
null_model_SC_CAMM_covariates<-lme(SC ~ SES+Age_at_Menarche,
                        method="ML",
                        random = ~1|tagid,
                        data=long_HonorsData %>% 
                          filter(!is.na(SC),
                                 !is.na(SES),
                                 !is.na(CAMM_lag),
                                  !is.na(SC_lag),
                                 !is.na(Age_at_Menarche)
                              ))

lin_model_SC_CAMM_covariates<-lme(SC ~ SES+Age_at_Menarche+SC_lag+CAMM_lag,
                       method="ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>% 
                         filter(!is.na(SC),
                                !is.na(SES),
                                !is.na(SC_lag),
                                !is.na(CAMM_lag),
                                !is.na(Age_at_Menarche)))

lin_model_SC_covariates<-(lme(SC ~ SES+Age_at_Menarche+SC_lag,
                       method="ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>% 
                         filter(!is.na(SC),
                                !is.na(SES),
                                !is.na(SC_lag),
                                !is.na(CAMM_lag),
                                !is.na(Age_at_Menarche))))

summary(lin_model_SC_CAMM)
anova(null_model_SC_CAMM_covariates,lin_model_SC_covariates,lin_model_SC_CAMM_covariates)
anova(lin_model_SC_CAMM_covariates)
############################################


# #### Subsequent exploratory examination to see what maybe driving the lack of relationship between
# # prior CAMM and SC when SC_lag is added but only in the non-covariate model
# 
# # Null model filtering NAs in contemporaneous measures of SC and CAMM
 null_model_contempSC<-lme(SC ~ 1,
                      method="ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>%
                               filter(!is.na(SC),
                                      !is.na(CAMM_lag),
                                      !is.na(SC_lag)))

## Academic acheivement and self-perceived scholastic competence 

null_model_aa_SC <- lme(SC ~ 1, 
                        method="ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>%
                               filter(!is.na(SC),
                                      !is.na(Grades)))
                       
lin_model_aa_SC <- lme(SC ~ Grades, 
                        method="ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>%
                               filter(!is.na(SC),
                                      !is.na(Grades)))

## SES and self-perceived scholastic competence 

null_model_ses_SC <- lme(SC ~ 1, 
                        method="ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>%
                               filter(!is.na(SC),
                                      !is.na(SES)))

lin_model_ses_SC <- lme(SC ~ SES, 
                        method="ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>%
                               filter(!is.na(SC),
                                      !is.na(SES)))
                                
## Linear model of prior CAMM predicting SC

 null_model_camm <- lme(SC ~ 1,
                       method ="ML",
                       random = ~1|tagid,
                       data = long_HonorsData %>%
                               filter(!is.na(SC),
                                      !is.na(SC_lag),
                                      !is.na(CAMM_lag)))
 lin_model_CAMM<-lme(SC ~ CAMM_lag,
                       method="ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>%
                               filter(!is.na(SC),
                                      !is.na(SC_lag),
                                      !is.na(CAMM_lag)))
# # Linear model of prior SC predicting SC
 lin_model_baselinSC<-lme(SC ~ SC_lag,
                       method="ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>%
                                filter(!is.na(SC),
                                       !is.na(SC_lag),
                                       !is.na(CAMM_lag)))
 
# # Linear model of CAMM predicting SC (contemporaneous measurements)
 lin_model_contempSC_CAMM<-lme(SC ~ CAMM,
                       method="ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>%
                               filter(!is.na(SC),
                                      !is.na(CAMM),
                                      !is.na(CAMM_lag),
                                      !is.na(SC_lag)))
 
 lin_model_SC_CAMM_controlled<-lme(SC ~ SC_lag + CAMM_lag + CAMM,
                       method="ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>%
                               filter(!is.na(SC),
                                      !is.na(CAMM),
                                      !is.na(CAMM_lag),
                                      !is.na(SC_lag)))
 
# 
# # Compare basic null to contemporaneous measurements model
# anova(null_model_contempSC,lin_model_contempSC_CAMM,lin_model_SC_CAMM_controlled)
# summary(lin_model_SC_CAMM_controlled)


#Q3: Are levels of scholastic competence predicted by transitioning into middle school or high school?

# Transition recoded 0=1, 1=2, 0=2=0 and then 1=TranMiddle; 0=NoTran; 2=TranHigh

long_HonorsData <- long_HonorsData%>%
  mutate(Transition=ifelse(Transition==0, 1,
                           ifelse(Transition==1, 2,
                                  ifelse(Transition==2,0,
                              Transition)))) %>%
  mutate(Transition=as.factor(Transition))
 
# use in analysis, don't use to make table 1 
long_HonorsData<-long_HonorsData %>%
mutate(Transition=ifelse(Transition==1,"TranMiddle",
                          ifelse(Transition==0,"NoTran",
                                 ifelse(Transition==2,"TranHigh",
                          Transition)))) %>%
 mutate(Transition=as.factor(Transition))

levels(long_HonorsData$Transition)


null_model_SC_Transition<-lme(SC ~ 1,
                      method="ML",
                      random = ~1|tagid,
                      data=long_HonorsData %>% 
                              filter(!is.na(SC),
                                !is.na(SC_lag),
                                !is.na(Transition)))

lin_model_SC_Transition<-lme(SC ~ SC_lag + Transition,
                      method="ML",
                      random = ~1|tagid,
                      data=long_HonorsData %>% 
                              filter(!is.na(SC),
                                !is.na(SC_lag),
                                !is.na(Transition)))


summary(lin_model_SC_Transition)
anova(null_model_SC_Transition,lin_model_SC_Transition)

# plotting transitions with covariates 

data = long_HonorsData %>% 
  filter(!is.na(SC),
         !is.na(SES),
         !is.na(Transition),
         !is.na(Age_at_Menarche))

# get predicted values for each individual and the fixed effect 

model_to_plot = lmer(SC ~ SES + Age_at_Menarche + SC_lag + Transition + (1|tagid), data = data)

# get mean ages per transition

age_means = data %>%
  group_by(Transition) %>%
  summarize(Age_at_Wave = mean(Age_at_Wave, na.rm = TRUE))

# use fixed effect CIs from the model
cis = ggeffects::ggpredict(model_to_plot, c("Transition")) %>%
  data.frame() %>%
  rename("Transition" = x) %>%
  left_join(., age_means)

# plot against age

transitions <- ggplot(data=data,
       aes(x=Age_at_Wave,
           y=SC))+
  xlab("Age (years)")+
  ylab("Scholastic Competence")+
  geom_line(aes(group=tagid,colour=Transition),size=.3,alpha=0.3)+
  geom_point(aes(group=tagid,colour=Transition, shape=Transition),size=2,alpha=0.3)+
  geom_crossbar(data = cis, aes(x = Age_at_Wave, y = predicted, color = Transition,
                           ymin = conf.low, ymax = conf.high), width = 0.4) +
  scale_color_manual(name="Transition",
                     labels= c("No Transition",
                               "Middle School",
                               "High School"),
                     values = c("orange", "purple", "blue")) +
  scale_shape(name= "Transition",
              labels=c("No Transition",
                       "Middle School",
                       "High School")) +
  theme(legend.position="bottom",
        legend.box = "horizontal",
        axis.title = element_text(face = "bold"),
        legend.text = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme_minimal()

  
ggsave("Transitions_by_SC.tiff", units= 'in', dpi=600, bg = "transparent")


## Add covariates

null_SC_Transition_covariates<-lme(SC ~ SES+Age_at_Menarche,
                        method="ML",
                        random = ~1|tagid,
                        data=long_HonorsData %>% 
                          filter(!is.na(SC),
                                 !is.na(SES),
                                 !is.na(SC_lag),
                                 !is.na(Transition),
                                 !is.na(Age_at_Menarche)))

lin_SC_Transition_covariates<-lme(SC ~ SES+Age_at_Menarche+SC_lag+Transition,
                       method = "ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>% 
                         filter(!is.na(SC),
                                !is.na(SES),
                                !is.na(SC_lag),
                                !is.na(Transition),
                                !is.na(Age_at_Menarche)))



summary(lin_SC_Transition_covariates)
anova(null_SC_Transition_covariates,lin_SC_Transition_covariates)

```

```{r}
# making a mean centered age variable 

long_HonorsData$agecenter<-(long_HonorsData$Age_at_Wave-12.5)
long_HonorsData$agecenter.sq<-(long_HonorsData$agecenter*long_HonorsData$agecenter)

## add random slope to age question, compare models w/ and w/o to see best fit

#mean_age <- long_HonorsData %>%
  #group_by(tagid) %>%
  #summarise(mean_age = mean(Age_at_Wave))

#long_HonorsData <- full_join(long_HonorsData, mean_age, by=c("tagid")) %>%
  #distinct(.)


#Q1: Does self-perceived scholastic competence change across early adolescence in girls?  

null_model_SC_age_cov<-lme(SC ~ SES+Age_at_Menarche+Grades,
                      method="ML",
                      random = ~1 | tagid,
                      data=long_HonorsData %>% 
                              filter(!is.na(SC),
                                     !is.na(agecenter),
                                     !is.na(SES),
                                     !is.na(Age_at_Menarche),
                                     !is.na(Grades)))

lin_model_SC_age_cov<-lme(SC ~ SES+Age_at_Menarche+agecenter+Grades,
                      method="ML",
                      random = ~1 | tagid,
                      data=long_HonorsData %>% 
                              filter(!is.na(SC),
                                     !is.na(agecenter),
                                     !is.na(SES),
                                     !is.na(Age_at_Menarche),
                                     !is.na(Grades)))
summary(lin_model_SC_age_cov)

quad_model_SC_age_cov<-lme(SC ~ SES+Age_at_Menarche+Grades+agecenter+agecenter.sq,
                      method="ML",
                      random = ~1|tagid,
                      data=long_HonorsData %>% 
                             filter(!is.na(SC),
                                     !is.na(agecenter),
                                     !is.na(SES),
                                     !is.na(Age_at_Menarche),
                                    !is.na(Grades)))

# question 2 w/ grades

null_model_SC_CAMM_covariates<-lme(SC ~ SES+Age_at_Menarche+Grades,
                        method="ML",
                        random = ~1|tagid,
                        data=long_HonorsData %>% 
                          filter(!is.na(SC),
                                 !is.na(SES),
                                 !is.na(CAMM_lag),
                                  !is.na(SC_lag),
                                 !is.na(Age_at_Menarche),
                                 !is.na(Grades)
                              ))

lin_model_SC_CAMM_covariates<-lme(SC ~ SES+Age_at_Menarche+Grades+SC_lag+CAMM_lag,
                       method="ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>% 
                         filter(!is.na(SC),
                                !is.na(SES),
                                !is.na(SC_lag),
                                !is.na(CAMM_lag),
                                !is.na(Age_at_Menarche),
                                !is.na(Grades)))

lin_model_SC_covariates<-(lme(SC ~ SES+Age_at_Menarche+SC_lag,
                       method="ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>% 
                         filter(!is.na(SC),
                                !is.na(SES),
                                !is.na(SC_lag),
                                !is.na(CAMM_lag),
                                !is.na(Age_at_Menarche))))

summary(lin_model_SC_CAMM)
anova(null_model_SC_CAMM_covariates,lin_model_SC_covariates,lin_model_SC_CAMM_covariates)
anova(lin_model_SC_CAMM_covariates)

# question three w/ grades

null_SC_Transition_covariates<-lme(SC ~ SES+Age_at_Menarche+Grades,
                        method="ML",
                        random = ~1|tagid,
                        data=long_HonorsData %>% 
                          filter(!is.na(SC),
                                 !is.na(SES),
                                 !is.na(SC_lag),
                                 !is.na(Transition),
                                 !is.na(Age_at_Menarche),
                                 !is.na(Grades)))

lin_SC_Transition_covariates<-lme(SC ~ SES+Age_at_Menarche+Grades+SC_lag+Transition,
                       method = "ML",
                       random = ~1|tagid,
                       data=long_HonorsData %>% 
                         filter(!is.na(SC),
                                !is.na(SES),
                                !is.na(SC_lag),
                                !is.na(Transition),
                                !is.na(Age_at_Menarche),
                                !is.na(Grades)))


### trying to figure out how to run sppa predicting grades 

install.packages("ordinal")
install.packages("devtools")
library("ordinal")

long_HonorsData$Grades_ordered <- as.ordered(long_HonorsData$Grades)

sppa_grades <- clmm(Grades_ordered ~ SC_lag + (1 | tagid), data = long_HonorsData, link = "logit", Hess=TRUE) 

## look at concurrent SPPA-SC too, report z-value & p of both

grades_sppa <- clmm(Grades_ordered ~ SC + (1 | tagid), data = long_HonorsData, Hess=TRUE) 

##nulls 

sppa_grades.null <- clmm(Grades_ordered ~ 1 + (1 | tagid), data = long_HonorsData, Hess = TRUE)

grades_sppa.null <- clmm(Grades_ordered ~ 1 + (1 | tagid), data = long_HonorsData, Hess=TRUE) 

(ci <- confint(sppa_grades))
exp(cbind(OR = coef(sppa_grades), ci))
ctable <- exp(coef(sppa_grades))

(ci <- confint(grades_sppa))
exp(cbind(OR = coef(grades_sppa), ci))
ctable <- exp(coef(grades_sppa))

```




Creating Descriptive Tables 
```{r}

library(dplyr)

descriptives_CAMM <- long_HonorsData %>% group_by(wave) %>%
  summarize(
    Mean = mean(CAMM, na.rm= TRUE)
    , Median = median(CAMM, na.rm = TRUE)
    , SD = sd(CAMM, na.rm = TRUE)
    , Min = min(CAMM, na.rm = TRUE)
    , Max = max(CAMM, na.rm = TRUE)
  )

descriptives_SC <- long_HonorsData %>% group_by(wave) %>%
  summarize(
    Mean = mean(SC, na.rm= TRUE)
    , Median = median(SC, na.rm = TRUE)
    , SD = sd(SC, na.rm = TRUE)
    , Min = min(SC, na.rm = TRUE)
    , Max = max(SC, na.rm = TRUE)
  )

descriptives_age <- long_HonorsData %>% group_by(wave) %>%
  summarize(
    Mean = mean(Age_at_Wave, na.rm= TRUE)
    , Median = median(Age_at_Wave, na.rm = TRUE)
    , SD = sd(Age_at_Wave, na.rm = TRUE)
    , Min = min(Age_at_Wave, na.rm = TRUE)
    , Max = max(Age_at_Wave, na.rm = TRUE)
  )

long_HonorsData$wave <- 
  factor(long_HonorsData$wave, 
         levels= c(1, 2, 3),
         labels = c("Wave 1", 
                    "Wave 2", 
                    "Wave 3"))

long_HonorsData$Transition <- 
  factor(long_HonorsData$Transition, levels=c(0, 1, 2),
         labels=c("No Transition",
                  "Transitioned to Middle School",
                  "Transitioned to High School"))

label(long_HonorsData$Age_at_Wave) <- "Age"
label(long_HonorsData$CAMM) <- "Child and Adolescent Mindfulnes Measure scores"
label(long_HonorsData$SC) <- "Self-Perceived Scholastic Competence"

units(long_HonorsData$Age_at_Wave) <- "years"

table1(~ Transition + Age_at_Wave + CAMM + SC | wave, data=long_HonorsData, overall = "Total", topclass = "Rtable1-grid Rtable1-shade Rtable1-times")





```

